### PR TITLE
Add dict to ionic_steps typing

### PR DESCRIPTION
**Pull request by orionarcher**
By adding `"ionic_steps"` to `DATA_OBJECTS` it changes the possible types. This is a small fix for that

### CODE REVIEW

**Comment by orionarcher** [comment]
@esoteric-ephemera I made a small oversight in my last PR, this should fix it.

**Comment by esoteric-ephemera** [comment]
Hey Orion, I think I may have fixed this separately, can you double check that the ionic_steps are correctly stored as blobs?

**Comment by orionarcher** [comment]
I just pulled the recent changes and I think this fix is still necessary. I am still getting an error when trying to reconstitute the doc as a pydantic object. Broadening the type to include dict fixed it for me.

```python
dict_doc = doc["output"]
task_doc = ForceFieldTaskDocument.parse_obj(dict_doc)
```

```
Traceback (most recent call last):
  File "/Users/orioncohen/miniforge3/envs/radical/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-ba8e139772af>", line 8, in <module>
    task_doc = ForceFieldTaskDocument.parse_obj(dict_doc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/miniforge3/envs/radical/lib/python3.11/site-packages/pydantic/main.py", line 1135, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/orioncohen/miniforge3/envs/radical/lib/python3.11/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ForceFieldTaskDocument
output.ionic_steps
  Input should be a valid list [type=list_type, input_value={'@class': '', '@module':...48118', 'store': 'data'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type
```

**Comment by esoteric-ephemera** [comment]
Very strange - I'm not getting these errors trying to reconstruct the doc (tried a few pydantic v2.7.x and 2.8.x) and ionic steps should be a list of dict when deserialized. Can you double check that `doc["output"]["output"]["ionic_steps"]` is a list or null, and that `ForcefieldTaskDoc(**doc["output"])` also hydrates correctly?

**Comment by orionarcher** [comment]
Do you have an additional data store configured in your test environment? If not, we won't see the same behavior. I am getting `ionic_steps` saved as a reference to it's location in the additional store:

```python
>>> doc["output"]["output"]["ionic_steps"]
{'@class': '',
 '@module': '',
 'blob_uuid': '3e24b30f-97f3-40db-aeb7-266e0ca48118',
 'store': 'data'}
```

I checked and ForcefieldTaskDoc(**doc["output"]) hydrates correctly.

**Comment by esoteric-ephemera** [comment]
Oh OK I see - specifying "output.ionic_steps" in the additional store data does not actually push ionic_steps to blob storage, but "ionic_steps" does

**Pull request merged**
